name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build Spring Boot app with Maven
      working-directory: ./server  # Assurez-vous que vous êtes dans le bon répertoire de votre serveur Spring Boot
      run: mvn clean install -DskipTests

    - name: Build React Docker image
      working-directory: ./clinet 
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

    - name: Build Spring Boot Docker image
      working-directory: ./server  # Assurez-vous que vous êtes dans le bon répertoire de votre serveur Spring Boot
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest .

    - name: Push React Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    - name: Push Spring Boot Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-app:latest
